name: Gearsystem CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  linux:
    name: Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Update OS
      run: sudo apt-get update -qq
    - name: Install dependencies
      run: sudo apt-get install -y libsdl2-dev libglew-dev libgtk-3-dev
    - name: make
      run: make
      working-directory: platforms/linux
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Linux (Ubuntu) binary
        path: platforms/linux/gearsystem
  libretro:
    name: Libretro (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: make
      run: make
      working-directory: platforms/libretro
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Libretro (Linux) core
        path: platforms/libretro/gearsystem_libretro.so
  macos:
    name: macOS
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: brew install sdl2
    - name: make
      run: make dist
      working-directory: platforms/macos
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: macOS App bundle
        path: platforms/macos/Gearsystem.app
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Get git version
      id: gitversion
      shell: bash
      run: echo "gitversion=$(git describe --abbrev=7 --dirty --always --tags)" >> $GITHUB_OUTPUT
    - name: msbuild
      run: msbuild Gearsystem.sln /t:Clean,Build /p:EmulatorBuild="${{ steps.gitversion.outputs.gitversion }}" /p:Configuration=Release
      working-directory: platforms/windows
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Windows binary
        path: platforms/windows/release/Gearsystem.exe
  bsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: make
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: pkg install -y git gmake pkgconf SDL2 glew lang/gcc gtk3
        run: |
          cd platforms/bsd
          gmake
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: BSD (FreeBSD) binary
        path: platforms/bsd/gearsystem
